### ISSUE TITLE
Add template for basic PyHARP project.

### ISSUE THREAD

**Issue by cwitkowitz** [audacitorch/pyharp#4]
In addition to the README tutorial, I think it would be really helpful to users of HARP if we included a barebones `template` project with indications such as:
- `<YOUR MODEL INITIALIZATION CODE HERE>`
- `<YOUR AUDIO LOADING CODE HERE>` (can provide default code)
- `<YOUR AUDIO PROCESSING CODE HERE>`
- `<YOUR AUDIO SAVING CODE HERE>` (can provide default code)
- `<YOUR UI ELEMENTS HERE>`

This would help delineate between what code is necessary to adhere to the expectations of HARP and what code should be provided by the user to perform audio processing.

I am thinking this project would include the minimum code (`app.py`) and extra files (`requirements.txt`, `.gitignore`, etc.) such that users can simply insert the specifics of their model/algorithm and then upload their working and HARP-ready application to HuggingFace.

**Comment by cwitkowitz** [comment]
Addressed by PR https://github.com/audacitorch/pyharp/pull/11 ...

**Comment by oreillyp** [comment]
Closed after merge
