### ISSUE TITLE
Best-practices for pre-trained models.

### ISSUE THREAD

**Issue by cwitkowitz** [audacitorch/pyharp#6]
It might be nice to mention best-practices for utilizing pre-trained models in cases where users plan to leverage models/algorithms that are not easily accessible through python packages.
- Store within repository using [Git Large File Storage](https://git-lfs.com/)
- Where to initialize models/algorithms (_i.e._, outside of `process_fn`)

**Comment by cwitkowitz** [comment]
Added in PR https://github.com/audacitorch/pyharp/pull/10 ...

**Comment by oreillyp** [comment]
Closed after merge
